// <auto-generated />
namespace TechnologyUniversity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class viewResult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(viewResult));
        
        string IMigrationMetadata.Id
        {
            get { return "201408212209122_viewResult"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
